-- phpMyAdmin SQL Dump
-- version 4.1.14
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Aug 14, 2014 at 11:07 PM
-- Server version: 5.6.17
-- PHP Version: 5.5.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `onlinecamerashop`
--

-- --------------------------------------------------------

--
-- Table structure for table `ipn_orders`
--

CREATE TABLE IF NOT EXISTS `ipn_orders` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `notify_version` varchar(64) DEFAULT NULL COMMENT 'IPN Version Number',
  `verify_sign` varchar(127) DEFAULT NULL COMMENT 'Encrypted string used to verify the authenticityof the tansaction',
  `test_ipn` int(11) DEFAULT NULL,
  `protection_eligibility` varchar(24) DEFAULT NULL COMMENT 'Which type of seller protection the buyer is protected by',
  `charset` varchar(127) DEFAULT NULL COMMENT 'Character set used by PayPal',
  `btn_id` varchar(40) DEFAULT NULL COMMENT 'The PayPal buy button clicked',
  `address_city` varchar(40) DEFAULT NULL COMMENT 'City of customers address',
  `address_country` varchar(64) DEFAULT NULL COMMENT 'Country of customers address',
  `address_country_code` varchar(2) DEFAULT NULL COMMENT 'Two character ISO 3166 country code',
  `address_name` varchar(128) DEFAULT NULL COMMENT 'Name used with address (included when customer provides a Gift address)',
  `address_state` varchar(40) DEFAULT NULL COMMENT 'State of customer address',
  `address_status` varchar(20) DEFAULT NULL COMMENT 'confirmed/unconfirmed',
  `address_street` varchar(200) DEFAULT NULL COMMENT 'Customer''s street address',
  `address_zip` varchar(20) DEFAULT NULL COMMENT 'Zip code of customer''s address',
  `first_name` varchar(64) DEFAULT NULL COMMENT 'Customer''s first name',
  `last_name` varchar(64) DEFAULT NULL COMMENT 'Customer''s last name',
  `payer_business_name` varchar(127) DEFAULT NULL COMMENT 'Customer''s company name, if customer represents a business',
  `payer_email` varchar(127) DEFAULT NULL COMMENT 'Customer''s primary email address. Use this email to provide any credits',
  `payer_id` varchar(13) DEFAULT NULL COMMENT 'Unique customer ID.',
  `payer_status` varchar(20) DEFAULT NULL COMMENT 'verified/unverified',
  `contact_phone` varchar(20) DEFAULT NULL COMMENT 'Customer''s telephone number.',
  `residence_country` varchar(2) DEFAULT NULL COMMENT 'Two-Character ISO 3166 country code',
  `business` varchar(127) DEFAULT NULL COMMENT 'Email address or account ID of the payment recipient (that is, the merchant). Equivalent to the values of receiver_email (If payment is sent to primary account) and business set in the Website Payment HTML.',
  `receiver_email` varchar(127) DEFAULT NULL COMMENT 'Primary email address of the payment recipient (that is, the merchant). If the payment is sent to a non-primary email address on your PayPal account, the receiver_email is still your primary email.',
  `receiver_id` varchar(13) DEFAULT NULL COMMENT 'Unique account ID of the payment recipient (i.e., the merchant). This is the same as the recipients referral ID.',
  `custom` varchar(255) DEFAULT NULL COMMENT 'Custom value as passed by you, the merchant. These are pass-through variables that are never presented to your customer.',
  `invoice` varchar(127) DEFAULT NULL COMMENT 'Pass through variable you can use to identify your invoice number for this purchase. If omitted, no variable is passed back.',
  `memo` varchar(255) DEFAULT NULL COMMENT 'Memo as entered by your customer in PayPal Website Payments note field.',
  `tax` decimal(10,2) DEFAULT NULL COMMENT 'Amount of tax charged on payment',
  `auth_id` varchar(19) DEFAULT NULL COMMENT 'Authorization identification number',
  `auth_exp` varchar(28) DEFAULT NULL COMMENT 'Authorization expiration date and time, in the following format: HH:MM:SS DD Mmm YY, YYYY PST',
  `auth_amount` int(11) DEFAULT NULL COMMENT 'Authorization amount',
  `auth_status` varchar(20) DEFAULT NULL COMMENT 'Status of authorization',
  `num_cart_items` int(11) DEFAULT NULL COMMENT 'If this is a PayPal shopping cart transaction, number of items in the cart',
  `parent_txn_id` varchar(19) DEFAULT NULL COMMENT 'In the case of a refund, reversal, or cancelled reversal, this variable contains the txn_id of the original transaction, while txn_id contains a new ID for the new transaction.',
  `payment_date` varchar(28) DEFAULT NULL COMMENT 'Time/date stamp generated by PayPal, in the following format: HH:MM:SS DD Mmm YY, YYYY PST',
  `payment_status` varchar(20) DEFAULT NULL COMMENT 'Payment status of the payment',
  `payment_type` varchar(10) DEFAULT NULL COMMENT 'echeck/instant',
  `pending_reason` varchar(20) DEFAULT NULL COMMENT 'This variable is only set if payment_status=pending',
  `reason_code` varchar(20) DEFAULT NULL COMMENT 'This variable is only set if payment_status=reversed',
  `remaining_settle` int(11) DEFAULT NULL COMMENT 'Remaining amount that can be captured with Authorization and Capture',
  `shipping_method` varchar(64) DEFAULT NULL COMMENT 'The name of a shipping method from the shipping calculations section of the merchants account profile. The buyer selected the named shipping method for this transaction',
  `shipping` decimal(10,2) DEFAULT NULL COMMENT 'Shipping charges associated with this transaction. Format unsigned, no currency symbol, two decimal places',
  `transaction_entity` varchar(20) DEFAULT NULL COMMENT 'Authorization and capture transaction entity',
  `txn_id` varchar(19) DEFAULT NULL COMMENT 'A unique transaction ID generated by PayPal',
  `txn_type` varchar(20) DEFAULT NULL COMMENT 'cart/express_checkout/send-money/virtual-terminal/web-accept',
  `exchange_rate` decimal(10,2) DEFAULT NULL COMMENT 'Exchange rate used if a currency conversion occured',
  `mc_currency` varchar(3) DEFAULT NULL COMMENT 'Three character country code. For payment IPN notifications, this is the currency of the payment, for non-payment subscription IPN notifications, this is the currency of the subscription.',
  `mc_fee` decimal(10,2) DEFAULT NULL COMMENT 'Transaction fee associated with the payment, mc_gross minus mc_fee equals the amount deposited into the receiver_email account. Equivalent to payment_fee for USD payments. If this amount is negative, it signifies a refund or reversal, and either ofthose p',
  `mc_gross` decimal(10,2) DEFAULT NULL COMMENT 'Full amount of the customer''s payment',
  `mc_handling` decimal(10,2) DEFAULT NULL COMMENT 'Total handling charge associated with the transaction',
  `mc_shipping` decimal(10,2) DEFAULT NULL COMMENT 'Total shipping amount associated with the transaction',
  `payment_fee` decimal(10,2) DEFAULT NULL COMMENT 'USD transaction fee associated with the payment',
  `payment_gross` decimal(10,2) DEFAULT NULL COMMENT 'Full USD amount of the customers payment transaction, before payment_fee is subtracted',
  `settle_amount` decimal(10,2) DEFAULT NULL COMMENT 'Amount that is deposited into the account''s primary balance after a currency conversion',
  `settle_currency` varchar(3) DEFAULT NULL COMMENT 'Currency of settle amount. Three digit currency code',
  `auction_buyer_id` varchar(64) DEFAULT NULL COMMENT 'The customer''s auction ID.',
  `auction_closing_date` varchar(28) DEFAULT NULL COMMENT 'The auction''s close date. In the format: HH:MM:SS DD Mmm YY, YYYY PSD',
  `auction_multi_item` int(11) DEFAULT NULL COMMENT 'The number of items purchased in multi-item auction payments',
  `for_auction` varchar(10) DEFAULT NULL COMMENT 'This is an auction payment - payments made using Pay for eBay Items or Smart Logos - as well as send money/money request payments with the type eBay items or Auction Goods(non-eBay)',
  `subscr_date` varchar(28) DEFAULT NULL COMMENT 'Start date or cancellation date depending on whether txn_type is subcr_signup or subscr_cancel',
  `subscr_effective` varchar(28) DEFAULT NULL COMMENT 'Date when a subscription modification becomes effective',
  `period1` varchar(10) DEFAULT NULL COMMENT '(Optional) Trial subscription interval in days, weeks, months, years (example a 4 day interval is 4 D',
  `period2` varchar(10) DEFAULT NULL COMMENT '(Optional) Trial period',
  `period3` varchar(10) DEFAULT NULL COMMENT 'Regular subscription interval in days, weeks, months, years',
  `amount1` decimal(10,2) DEFAULT NULL COMMENT 'Amount of payment for Trial period 1 for USD',
  `amount2` decimal(10,2) DEFAULT NULL COMMENT 'Amount of payment for Trial period 2 for USD',
  `amount3` decimal(10,2) DEFAULT NULL COMMENT 'Amount of payment for regular subscription  period 1 for USD',
  `mc_amount1` decimal(10,2) DEFAULT NULL COMMENT 'Amount of payment for trial period 1 regardless of currency',
  `mc_amount2` decimal(10,2) DEFAULT NULL COMMENT 'Amount of payment for trial period 2 regardless of currency',
  `mc_amount3` decimal(10,2) DEFAULT NULL COMMENT 'Amount of payment for regular subscription period regardless of currency',
  `recurring` varchar(1) DEFAULT NULL COMMENT 'Indicates whether rate recurs (1 is yes, blank is no)',
  `reattempt` varchar(1) DEFAULT NULL COMMENT 'Indicates whether reattempts should occur on payment failure (1 is yes, blank is no)',
  `retry_at` varchar(28) DEFAULT NULL COMMENT 'Date PayPal will retry a failed subscription payment',
  `recur_times` int(11) DEFAULT NULL COMMENT 'The number of payment installations that will occur at the regular rate',
  `username` varchar(64) DEFAULT NULL COMMENT '(Optional) Username generated by PayPal and given to subscriber to access the subscription',
  `password` varchar(24) DEFAULT NULL COMMENT '(Optional) Password generated by PayPal and given to subscriber to access the subscription (Encrypted)',
  `subscr_id` varchar(19) DEFAULT NULL COMMENT 'ID generated by PayPal for the subscriber',
  `case_id` varchar(28) DEFAULT NULL COMMENT 'Case identification number',
  `case_type` varchar(28) DEFAULT NULL COMMENT 'complaint/chargeback',
  `case_creation_date` varchar(28) DEFAULT NULL COMMENT 'Date/Time the case was registered',
  `order_status` enum('PAID','WAITING','REJECTED') DEFAULT NULL COMMENT 'Additional variable to make payment_status more actionable',
  `discount` decimal(10,2) DEFAULT NULL COMMENT 'Additional variable to record the discount made on the order',
  `shipping_discount` decimal(10,2) DEFAULT NULL COMMENT 'Record the discount made on the shipping',
  `ipn_track_id` varchar(127) DEFAULT NULL COMMENT 'Internal tracking variable added in April 2011',
  `transaction_subject` varchar(255) DEFAULT NULL COMMENT 'Describes the product for a button-based purchase',
  `dispatched_status` enum('1','0') NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UniqueTransactionID` (`txn_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=12 ;

--
-- Dumping data for table `ipn_orders`
--

INSERT INTO `ipn_orders` (`id`, `user_id`, `notify_version`, `verify_sign`, `test_ipn`, `protection_eligibility`, `charset`, `btn_id`, `address_city`, `address_country`, `address_country_code`, `address_name`, `address_state`, `address_status`, `address_street`, `address_zip`, `first_name`, `last_name`, `payer_business_name`, `payer_email`, `payer_id`, `payer_status`, `contact_phone`, `residence_country`, `business`, `receiver_email`, `receiver_id`, `custom`, `invoice`, `memo`, `tax`, `auth_id`, `auth_exp`, `auth_amount`, `auth_status`, `num_cart_items`, `parent_txn_id`, `payment_date`, `payment_status`, `payment_type`, `pending_reason`, `reason_code`, `remaining_settle`, `shipping_method`, `shipping`, `transaction_entity`, `txn_id`, `txn_type`, `exchange_rate`, `mc_currency`, `mc_fee`, `mc_gross`, `mc_handling`, `mc_shipping`, `payment_fee`, `payment_gross`, `settle_amount`, `settle_currency`, `auction_buyer_id`, `auction_closing_date`, `auction_multi_item`, `for_auction`, `subscr_date`, `subscr_effective`, `period1`, `period2`, `period3`, `amount1`, `amount2`, `amount3`, `mc_amount1`, `mc_amount2`, `mc_amount3`, `recurring`, `reattempt`, `retry_at`, `recur_times`, `username`, `password`, `subscr_id`, `case_id`, `case_type`, `case_creation_date`, `order_status`, `discount`, `shipping_discount`, `ipn_track_id`, `transaction_subject`, `dispatched_status`, `created_at`, `updated_at`) VALUES
(5, 1, '3.8', 'AFcWxV21C7fd0v3bYYYRCpSSRl31AbViLsq3XQvTA4dc5NYfO0U4Ae7z', 1, 'Eligible', 'windows-1252', NULL, 'San Jose', 'United States', 'US', 'Yousaf Syed Ehsan', 'CA', 'confirmed', '1 Main St', '95131', 'Yousaf Syed', 'Ehsan', NULL, 'cloudgulf@gmail.com', 'YCHZ8QYA2AYYC', 'verified', NULL, 'US', 'mmesunny-facilitator@gmail.com', 'mmesunny-facilitator@gmail.com', '7EJLGM6TRX7YA', NULL, NULL, NULL, '0.00', NULL, NULL, NULL, NULL, 2, NULL, '05:03:20 Aug 13, 2014 PDT', 'Completed', 'instant', NULL, NULL, NULL, NULL, NULL, NULL, '74F14322235672501', 'cart', NULL, 'USD', '5.23', '170.00', '0.00', '40.00', '5.23', '170.00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PAID', '0.00', NULL, NULL, NULL, '1', '2014-08-13 14:04:58', '2014-08-13 14:39:06'),
(6, 1, '3.8', 'AFcWxV21C7fd0v3bYYYRCpSSRl31AmWlXFfmJJfFbBw427-raHGJ6zWj', 1, 'Eligible', 'windows-1252', NULL, 'San Jose', 'United States', 'US', 'Yousaf Syed Ehsan', 'CA', 'confirmed', '1 Main St', '95131', 'Yousaf Syed', 'Ehsan', NULL, 'cloudgulf@gmail.com', 'YCHZ8QYA2AYYC', 'verified', NULL, 'US', 'mmesunny-facilitator@gmail.com', 'mmesunny-facilitator@gmail.com', '7EJLGM6TRX7YA', NULL, NULL, NULL, '0.00', NULL, NULL, NULL, NULL, 2, NULL, '05:41:49 Aug 13, 2014 PDT', 'Completed', 'instant', NULL, NULL, NULL, NULL, NULL, NULL, '24U75373YB6125709', 'cart', NULL, 'USD', '5.23', '170.00', '0.00', '40.00', '5.23', '170.00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PAID', '0.00', NULL, NULL, NULL, '0', '2014-08-13 14:42:13', '2014-08-13 14:42:13'),
(7, 1, '3.8', 'AFcWxV21C7fd0v3bYYYRCpSSRl31AY3Qk.hfAZHqC4x.IDTVv5c8XpB8', 1, 'Eligible', 'windows-1252', NULL, 'San Jose', 'United States', 'US', 'Yousaf Syed Ehsan', 'CA', 'confirmed', '1 Main St', '95131', 'Yousaf Syed', 'Ehsan', NULL, 'cloudgulf@gmail.com', 'YCHZ8QYA2AYYC', 'verified', NULL, 'US', 'mmesunny-facilitator@gmail.com', 'mmesunny-facilitator@gmail.com', '7EJLGM6TRX7YA', NULL, NULL, NULL, '0.00', NULL, NULL, NULL, NULL, 4, NULL, '05:45:06 Aug 13, 2014 PDT', 'Completed', 'instant', NULL, NULL, NULL, NULL, NULL, NULL, '1WL23956LS774033V', 'cart', NULL, 'USD', '17.99', '610.00', '0.00', '80.00', '17.99', '610.00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PAID', '0.00', NULL, NULL, NULL, '1', '2014-08-13 14:45:34', '2014-08-13 14:45:34'),
(4, 1, '3.8', 'Aio-gQfyJCvVjQ2xkTFpSfI.wlAgADwhoQlneukbrfXjuXS8yd2vMdK0', 1, 'Eligible', 'windows-1252', NULL, 'San Jose', 'United States', 'US', 'Yousaf Syed Ehsan', 'CA', 'confirmed', '1 Main St', '95131', 'Yousaf Syed', 'Ehsan', NULL, 'cloudgulf@gmail.com', 'YCHZ8QYA2AYYC', 'verified', NULL, 'US', 'mmesunny-facilitator@gmail.com', 'mmesunny-facilitator@gmail.com', '7EJLGM6TRX7YA', NULL, NULL, NULL, '0.00', NULL, NULL, NULL, NULL, 2, NULL, '04:54:22 Aug 13, 2014 PDT', 'Completed', 'instant', NULL, NULL, NULL, NULL, NULL, NULL, '5YE81852L17838844', 'cart', NULL, 'USD', '5.23', '170.00', '0.00', '40.00', '5.23', '170.00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PAID', '0.00', NULL, NULL, NULL, '0', '2014-08-13 13:55:05', '2014-08-13 13:55:05'),
(8, 1, '3.8', 'AdYqZzHgQkZYND5ekVEZ7fVT6KW5A7yEfKctI8T.EpNL3.PiGtE8nil6', 1, 'Eligible', 'windows-1252', NULL, 'San Jose', 'United States', 'US', 'Yousaf Syed Ehsan', 'CA', 'confirmed', '1 Main St', '95131', 'Yousaf Syed', 'Ehsan', NULL, 'cloudgulf@gmail.com', 'YCHZ8QYA2AYYC', 'verified', NULL, 'US', 'mmesunny-facilitator@gmail.com', 'mmesunny-facilitator@gmail.com', '7EJLGM6TRX7YA', NULL, NULL, NULL, '0.00', NULL, NULL, NULL, NULL, 2, NULL, '05:58:25 Aug 13, 2014 PDT', 'Completed', 'instant', NULL, NULL, NULL, NULL, NULL, NULL, '4GE201251G7435639', 'cart', NULL, 'USD', '5.23', '170.00', '0.00', '40.00', '5.23', '170.00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PAID', '0.00', NULL, NULL, NULL, '1', '2014-08-13 14:58:53', '2014-08-13 14:58:53'),
(9, 1, '3.8', 'AFcWxV21C7fd0v3bYYYRCpSSRl31AW3o83Z8Gpaj6plDGCijbM.3DmGB', 1, 'Eligible', 'windows-1252', NULL, 'San Jose', 'United States', 'US', 'Yousaf Syed Ehsan', 'CA', 'confirmed', '1 Main St', '95131', 'Yousaf Syed', 'Ehsan', NULL, 'cloudgulf@gmail.com', 'YCHZ8QYA2AYYC', 'verified', NULL, 'US', 'mmesunny-facilitator@gmail.com', 'mmesunny-facilitator@gmail.com', '7EJLGM6TRX7YA', NULL, NULL, NULL, '0.00', NULL, NULL, NULL, NULL, 2, NULL, '06:44:47 Aug 13, 2014 PDT', 'Completed', 'instant', NULL, NULL, NULL, NULL, NULL, NULL, '1HY71113MB659733R', 'cart', NULL, 'USD', '5.23', '170.00', '0.00', '40.00', '5.23', '170.00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PAID', '0.00', NULL, NULL, NULL, '0', '2014-08-13 15:45:29', '2014-08-13 15:45:30'),
(10, 1, '3.8', 'ArPh16M2qo1OQo8p-iJ4GzOwciOFABeFUTR0phcS2SWNzPrjllW.mn7.', 1, 'Eligible', 'windows-1252', NULL, 'San Jose', 'United States', 'US', 'Yousaf Syed Ehsan', 'CA', 'confirmed', '1 Main St', '95131', 'Yousaf Syed', 'Ehsan', NULL, 'cloudgulf@gmail.com', 'YCHZ8QYA2AYYC', 'verified', NULL, 'US', 'mmesunny-facilitator@gmail.com', 'mmesunny-facilitator@gmail.com', '7EJLGM6TRX7YA', NULL, NULL, NULL, '0.00', NULL, NULL, NULL, NULL, 2, NULL, '06:47:34 Aug 13, 2014 PDT', 'Completed', 'instant', NULL, NULL, NULL, NULL, NULL, NULL, '7NS927040C803045F', 'cart', NULL, 'USD', '5.23', '170.00', '0.00', '40.00', '5.23', '170.00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PAID', '0.00', NULL, NULL, NULL, '1', '2014-08-13 15:48:43', '2014-08-13 15:48:43'),
(11, 1, '3.8', 'AFcWxV21C7fd0v3bYYYRCpSSRl31ApWylB-Q8CevIQSsspsLa5lepdty', 1, 'Eligible', 'windows-1252', NULL, 'San Jose', 'United States', 'US', 'Yousaf Syed Ehsan', 'CA', 'confirmed', '1 Main St', '95131', 'Yousaf Syed', 'Ehsan', NULL, 'cloudgulf@gmail.com', 'YCHZ8QYA2AYYC', 'verified', NULL, 'US', 'mmesunny-facilitator@gmail.com', 'mmesunny-facilitator@gmail.com', '7EJLGM6TRX7YA', NULL, NULL, NULL, '0.00', NULL, NULL, NULL, NULL, 4, NULL, '10:58:03 Aug 13, 2014 PDT', 'Completed', 'instant', NULL, NULL, NULL, NULL, NULL, NULL, '93W9662865626453E', 'cart', NULL, 'USD', '12.19', '410.00', '0.00', '80.00', '12.19', '410.00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PAID', '0.00', NULL, NULL, NULL, '1', '2014-08-13 19:58:36', '2014-08-13 19:58:37');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
